apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-workflow.fullname" . }}
  labels:
    {{- include "devops-workflow.labels" . | nindent 4 }}
data:
  config.json: |-
    {{ .Files.Get "files/config.json" | nindent 4}}