key: ENC[AES256_GCM,data:fe4zj6A=,iv:QRs6+PknGD1v/Lo++6WuLCpMWeD3xEBYxnlxvnlARWk=,tag:bQj3uBpET3qpVRR5LZTDPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-26T20:10:14Z"
    mac: ENC[AES256_GCM,data:0WKl9fTdf3ggIXwCzXAqvKcnT2+ZLmlyZERWSF5e05OWjshCdiNhsVdSx5Gp7Db8+ExHJv1ooA8DoLEZhvw6uUkI1+kd/W/llVNsLtigkxqpqPSIAZfS/x2epK42cCU5EsAk+eSqkhLRiG3r9TowI4T2LiSYdGae944Z+R3s0A8=,iv:bdLVadBA6UjeIgV28BmhJT39jVQbQm/7Cgk/msESbOQ=,tag:D0fP4eZ2fZ/4b2KpFO/kKQ==,type:str]
    pgp:
        - created_at: "2021-09-26T20:09:24Z"
          enc: "-----BEGIN PGP MESSAGE-----\r\n\r\nhQGMA00vq+DIvCeEAQv+MUsI1eHj0iJrfL0xjZegJMr7oJJSZmGHkkIXpObjB2dY\r\nOQ+08LorP8ZBNCV/f4j5VzrVSz9l0HYIObdHK8WJhGQ2ubrcm94VkVQ9S80F7P6G\r\nLbqT3qdDNUnrxRzZoXoyD1z6yI5DGMR0yZOuk2Y/uxvmgm63l28wilbCHaK2n2S8\r\nKm5wCFt7OjYcskkvNgkXkD/MsoNDS1NHol4UiDjpZXS+Y402YFgNWarRTxMi1sjF\r\neUYrZ+pFeIXnM+DGDCUhOATXYnHSLTWRgq/PTLdft9QqV6BkhYB6FTM1SpG1KgRN\r\nreRPq3J1EwasGd6Vq0mNCinvr8wgl+ZnBSm3L1u2XvICm9sFpJSNLkyuaV33b6jH\r\n3sL9M3IB7RA9ibcrTRx48hfzMN0K6uH+Optxfu+mcgBj5FYYp0sF9YHFBk5YT1Hh\r\nHipPCgTjn/YMfWbPNafrrhkm86il1wV42lEviq+datpU3BSrUZR/p+/FeRbG8mR2\r\nwAw64hnAocYDy+4Lv6Wz0l4Bxk5yQI9QjXrA9csk4gYCKS4FR8O7hUb88qso/2vc\r\n5H9LY7Dfop8PEkYvocUjC2zCnHRhjKAypG1vnOhmWB7cGEpAURDwROnV0TK1eedu\r\neFWI0LGcgFhW52cnEdHq\r\n=eQtt\r\n-----END PGP MESSAGE-----\r\n"
          fp: B1635CF0F15ABB4AA56056EDED497FDF7A1BF7DF
    unencrypted_suffix: _unencrypted
    version: 3.7.1
